const notes = [
  { noteName: "C", altName: "", freq: 32.7, keyboardKey: "q", type: "white" },
  {
    noteName: "C#",
    altName: "Db",
    freq: 34.65,
    keyboardKey: "2",
    type: "black",
    pressed: false,
  },
  { noteName: "D", altName: "", freq: 36.71, keyboardKey: "w", type: "white" },
  {
    noteName: "D#",
    altName: "Eb",
    freq: 38.89,
    keyboardKey: "3",
    type: "black",
    pressed: false,
  },
  { noteName: "E", altName: "", freq: 41.2, keyboardKey: "e", type: "white" },
  { noteName: "F", altName: "", freq: 43.65, keyboardKey: "r", type: "white" },
  { noteName: "F#", altName: "", freq: 46.25, keyboardKey: "5", type: "black" },
  { noteName: "G", altName: "", freq: 49.0, keyboardKey: "t", type: "white" },
  {
    noteName: "G#",
    altName: "Ab",
    freq: 51.91,
    keyboardKey: "6",
    type: "black",
    pressed: false,
  },
  { noteName: "A", altname: "", freq: 55.0, keyboardKey: "y", type: "white" },
  {
    noteName: "A#",
    altName: "Bb",
    freq: 110.1,
    keyboardKey: "7",
    type: "black",
    pressed: false,
  },
  { noteName: "B", altName: "", freq: 61.74, keyboardKey: "u", type: "white" },
  {
    noteName: "C",
    altName: "",
    octave: "2",
    freq: 65.41,
    keyboardKey: "i",
    type: "white",
    pressed: false,
  },
];
export default notes;
